### ISSUE TITLE
Air-gapped Trident installations fail due to incorrect version of csi-snapshotter referenced in docs.

### ISSUE THREAD

**Issue by jcurtis-netapp** [NetAppDocs/trident-2210#7]
### Page URL

https://docs.netapp.com/us-en/trident-2210/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions

### Page title

Docs reference wrong version of csi-snapshotter for air-gapped installations

### Summary

Customers attempting to install Trident 22.10 with volume snapshot support are instructed to install the incorrect container image:    registry.k8s.io/sig-storage/csi-snapshotter:v3.0.3 

The incorrect docs are not an issue for non air-gapped installations as the installer will automatically pull the correct csi-snapshotter version. Air gapped installs must pre stage the correct images in the image registry. Placing the csi-snapshotter:v3.0.3 in the image registry (as noted in the docs)  results Trident operator pod in image pullback state (failure state) due to wrong version of csi-snapshotter.

The version that is compatible with Trident 22.10 and Kubernetes v 1.21.X (and above)  is reported in the command **tridentctl images**   this command is built into the main trident binary and serves as a form of online docs but is not often referenced by administrators. 

We also confirmed by attempting to install Trident 22.10 running kubernetes v1.21.7. We observed Trident attempt to install the csi-snapshotter version 6.1.0

We request the documentation changed to match Tridents online docs (built into the system binary).

[root@rhel3 ~]# tridentctl images
[root@rhel3 trident-installer]# ./tridentctl images
+--------------------+--------------------------------------------------------------+
| KUBERNETES VERSION |                       CONTAINER IMAGE                        |
+--------------------+--------------------------------------------------------------+
| v1.20.0            | netapp/trident:22.10.0                                       |
|                    | docker.io/netapp/trident-autosupport:22.10                   |
|                    | registry.k8s.io/sig-storage/csi-provisioner:v3.3.0           |
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.0.0              |
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.6.0               |
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.1.0           |
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 |
|                    | netapp/trident-operator:22.10.0 (optional)                   |
+--------------------+--------------------------------------------------------------+
| **v1.21.0**  | netapp/trident:22.10.0                                       |
|                    | docker.io/netapp/trident-autosupport:22.10                   |
|                    | registry.k8s.io/sig-storage/csi-provisioner:v3.3.0           |
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.0.0              |
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.6.0               |
|                    | **registry.k8s.io/sig-storage/csi-snapshotter:v6.1.0**           |
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 |
|                    | netapp/trident-operator:22.10.0 (optional)                   |
+--------------------+--------------------------------------------------------------+
| v1.22.0            | netapp/trident:22.10.0                                       |
|                    | docker.io/netapp/trident-autosupport:22.10                   |
|                    | registry.k8s.io/sig-storage/csi-provisioner:v3.3.0           |
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.0.0              |
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.6.0               |
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.1.0           |
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 |
|                    | netapp/trident-operator:22.10.0 (optional)                   |
+--------------------+--------------------------------------------------------------+
| v1.23.0            | netapp/trident:22.10.0                                       |
|                    | docker.io/netapp/trident-autosupport:22.10                   |
|                    | registry.k8s.io/sig-storage/csi-provisioner:v3.3.0           |
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.0.0              |
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.6.0               |
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.1.0           |
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 |
|                    | netapp/trident-operator:22.10.0 (optional)                   |
+--------------------+--------------------------------------------------------------+
| v1.24.0            | netapp/trident:22.10.0                                       |
|                    | docker.io/netapp/trident-autosupport:22.10                   |
|                    | registry.k8s.io/sig-storage/csi-provisioner:v3.3.0           |
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.0.0              |
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.6.0               |
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.1.0           |
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 |
|                    | netapp/trident-operator:22.10.0 (optional)                   |
+--------------------+--------------------------------------------------------------+
| v1.25.0            | netapp/trident:22.10.0                                       |
|                    | docker.io/netapp/trident-autosupport:22.10                   |
|                    | registry.k8s.io/sig-storage/csi-provisioner:v3.3.0           |
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.0.0              |
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.6.0               |
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.1.0           |
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 |
|                    | netapp/trident-operator:22.10.0 (optional)                   |
+--------------------+--------------------------------------------------------------+

The incorrect table is noted in docs here:
https://docs.netapp.com/us-en/trident-2210/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@jcurtis-netapp Thank you for catching this! I've corrected the snapshotter version and the change will merge shortly.
